<?php

namespace Proxies\__CG__\Alivinatu\AlivinatuBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contacto extends \Alivinatu\AlivinatuBundle\Entity\Contacto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCalle($calle)
    {
        $this->__load();
        return parent::setCalle($calle);
    }

    public function getCalle()
    {
        $this->__load();
        return parent::getCalle();
    }

    public function setCiudad($ciudad)
    {
        $this->__load();
        return parent::setCiudad($ciudad);
    }

    public function getCiudad()
    {
        $this->__load();
        return parent::getCiudad();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setCelular($celular)
    {
        $this->__load();
        return parent::setCelular($celular);
    }

    public function getCelular()
    {
        $this->__load();
        return parent::getCelular();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setObservacion($observacion)
    {
        $this->__load();
        return parent::setObservacion($observacion);
    }

    public function getObservacion()
    {
        $this->__load();
        return parent::getObservacion();
    }

    public function setProvincia($provincia)
    {
        $this->__load();
        return parent::setProvincia($provincia);
    }

    public function getProvincia()
    {
        $this->__load();
        return parent::getProvincia();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'calle', 'ciudad', 'email', 'celular', 'telefono', 'observacion', 'provincia', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}