alivinatu:
    resource: "@AlivinatuBundle/Resources/config/routing.yml"
    prefix:   /

# rutas para el login  
login:
    pattern:  /login
    defaults: { _controller: 'AlivinatuBundle:Usuario:login' }

check_path:
    pattern: /check

logout:
    pattern:  /logout

# rutas para registrar el cliente
registroAdmin:
  pattern: /admin/registro
  defaults: { _controller: 'AlivinatuBundle:Usuario:registroAdmin' }
  
registroCliente:
  pattern: /user/registro
  defaults: { _controller: 'AlivinatuBundle:Usuario:registroCliente' }
  
# ruta para el menu del administrador
menuAdmin:
  pattern:  /admin
  defaults: { _controller: 'AlivinatuBundle:Admin:menuAdmin' }
    
# rutas para el CU de adminitrar cliente
adminCliente:
  pattern:  /admin/cliente
  defaults: { _controller: 'AlivinatuBundle:Admin:adminCliente' }
  
editarCliente:
  pattern:  /admin/editarCliente{id}
  defaults: { _controller: 'AlivinatuBundle:Admin:editarCliente' }
  
# rutas para el CU de administrar sala
adminSala:
  pattern:  /admin/sala
  defaults: { _controller: 'AlivinatuBundle:Admin:adminSala' }
  
registroSala:
  pattern:  /admin/registroSala
  defaults: { _controller: 'AlivinatuBundle:Admin:registroSala' }
  
editarSala:
  pattern:  /admin/editarSala{id}
  defaults: { _controller: 'AlivinatuBundle:Admin:editarSala' }

# rutas para el CU de administrar sala
adminServicio:
  pattern:  /admin/servicio
  defaults: { _controller: 'AlivinatuBundle:Admin:adminServicio' }
  
registroServicio:
  pattern:  /admin/registroServicio
  defaults: { _controller: 'AlivinatuBundle:Admin:registroServicio' }
  
editarServicio:
  pattern:  /admin/editarServicio{id}
  defaults: { _controller: 'AlivinatuBundle:Admin:editarServicio' }
  
  # rutas para el CU de administrar promociones
adminPromocion:
  pattern:  /admin/promocion
  defaults: { _controller: 'AlivinatuBundle:Admin:adminPromocion' }
  
registroPromocion:
  pattern:  /admin/registroPromocion
  defaults: { _controller: 'AlivinatuBundle:Admin:registroPromocion' }
  
editarPromocion:
  pattern:  /admin/editarPromocion{id}
  defaults: { _controller: 'AlivinatuBundle:Admin:editarPromocion' }

      
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


