<?php

namespace Alivinatu\AlivinatuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuotaRepository extends EntityRepository
{
}
