<?php

namespace Alivinatu\AlivinatuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionRepository extends EntityRepository
{
}
