<?php

namespace Alivinatu\AlivinatuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaRepository extends EntityRepository
{
}
