<?php

namespace Alivinatu\AlivinatuBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ControladorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Alivinatu\AlivinatuBundle\Controller\ControladorController();
        return $instance;
    }
}
